http:
  host: "0.0.0.0"
  port: 3000

app:
  env: "development"
  language: "en"
  debug: false
  prefix: "/api/v1"

  logger:
    http: false
    system: false

  hash:
    passwordSaltLength: 16

  auth:
    jwtSecretKey: "G23gsMcIsj"
    jwtExpiration: "1h"
    basicClientId: ""
    basicClientSecret: ""

db:
  postgres:
    host: "localhost"
    port: 5432
    username: ""
    password: ""
    name: "AIT_Test"

db-seed:
  products: 15
  users: 1
